"""Per-day species lists: everything the day's sites may offer, with a likelihood state and «интересная» flag.

Reads data/itinerary.json, data/sites_resolved.json (trip-report highlights = target_species),
data/site_species.json (GBIF autumn freq_aut and `state` per site, step gbif_sites),
data/species_index.json (endemic) and data/species/<id>.json (traits.range_restricted).
Writes data/study_lists.json:

  {date: {sites, species: [{id, state, interesting, why, freq_aut, new_for_route}]}}

The list is the union of the GBIF lists of the day's sites plus their highlights. Per species:
- state = best across the day's sites (sure > maybe > unlikely, see common.likelihood); a species
  missing from a site's GBIF list is "unlikely" there, so a highlight with no GBIF records is
  kept as "unlikely" (highlights are never dropped);
- why ⊆ {highlight (target_species of one of the day's sites), endemic (Colombian endemic),
  range_restricted (traits.range_restricted == 1)}; interesting = bool(why), independent of state;
- freq_aut = max over the day's sites (0 if none);
- new_for_route = not "sure"/"maybe" on any earlier day.
Sorted: interesting first, then sure > maybe > unlikely, then freq_aut desc, then id. No caps.
Also writes data/sources/study_lists_report.md (per-day counts).

Usage: uv run python run.py study
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from common import DATA, SOURCES, SPECIES_DIR, STATE_RANK, STATES, log, read_json, write_json, write_text  # noqa: E402


def main() -> None:
    itinerary = read_json(DATA / "itinerary.json")
    sites = {s["id"]: s for s in read_json(DATA / "sites_resolved.json")}
    site_sp = read_json(DATA / "site_species.json")
    index = {s["id"]: s for s in read_json(DATA / "species_index.json")}
    rr: set[str] = set()
    for p in SPECIES_DIR.glob("*.json"):
        sp = json.loads(p.read_text())
        if (sp.get("traits") or {}).get("range_restricted") == 1:
            rr.add(sp["id"])

    out: dict[str, dict] = {}
    seen: set[str] = set()  # sure/maybe on an earlier day
    rows = []
    for day in sorted(itinerary, key=lambda d: d["date"]):
        ids = [s for s in day.get("sites") or [] if s in sites]
        stats: dict[str, dict] = {}
        for sid in ids:
            for x in (site_sp.get(sid) or {}).get("species", []):
                cur = stats.setdefault(x["id"], {"state": "unlikely", "freq_aut": 0.0})
                if STATE_RANK[x["state"]] > STATE_RANK[cur["state"]]:
                    cur["state"] = x["state"]
                cur["freq_aut"] = max(cur["freq_aut"], x["freq_aut"])
        hl = {t for sid in ids for t in sites[sid].get("target_species", [])}
        for t in hl:
            stats.setdefault(t, {"state": "unlikely", "freq_aut": 0.0})

        lst = []
        for k, st in stats.items():
            if k not in index:
                continue
            why = [w for w, ok in (("highlight", k in hl), ("endemic", bool(index[k].get("endemic"))),
                                   ("range_restricted", k in rr)) if ok]
            lst.append({"id": k, "state": st["state"], "interesting": bool(why), "why": why,
                        "freq_aut": st["freq_aut"], "new_for_route": k not in seen})
        lst.sort(key=lambda x: (not x["interesting"], -STATE_RANK[x["state"]], -x["freq_aut"], x["id"]))
        seen |= {x["id"] for x in lst if x["state"] != "unlikely"}
        out[day["date"]] = {"sites": ids, "species": lst}
        cnt = {s: sum(1 for x in lst if x["state"] == s) for s in STATES}
        n_int = sum(1 for x in lst if x["interesting"])
        n_int_vis = sum(1 for x in lst if x["interesting"] and x["state"] != "unlikely")
        n_hl_unl = sum(1 for x in lst if "highlight" in x["why"] and x["state"] == "unlikely")
        rows.append((day["date"], ids, len(lst), cnt, n_int, n_int_vis, n_hl_unl))

    write_json(DATA / "study_lists.json", out)

    md = ["# Study lists report", "",
          "Generated by `pipeline/steps/build_study_lists.py`: per day, the union of the day's sites' GBIF species "
          "and highlights; state = best across the day's sites (thresholds in `pipeline/common.py`).", "",
          "| Date | Sites | Total | Sure | Maybe | Unlikely | Interesting (all / sure+maybe) | Highlights unlikely |",
          "|---|---|---|---|---|---|---|---|"]
    for d, ids, n, cnt, ni, niv, nhu in rows:
        md.append(f"| {d} | {', '.join(ids) or '-'} | {n} | {cnt['sure']} | {cnt['maybe']} | {cnt['unlikely']} | "
                  f"{ni} / {niv} | {nhu} |")
    write_text(SOURCES / "study_lists_report.md", "\n".join(md) + "\n")
    log(f"days: {len(rows)}, species per day max {max(r[2] for r in rows)}, "
        f"interesting per day max {max(r[4] for r in rows)}")


if __name__ == "__main__":
    main()
