"""Merge data/sources/*.json into data/species/<slug>.json, data/species_index.json, data/families.json.

Canonical taxonomy is eBird/Clements (matches Merlin and eBird in the field). The ACO checklist is the
canonical *list* of what occurs in Colombia and carries the status flags. Hand-written content lives in
content/species/<slug>.md and is merged at site build time, never here.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import DATA, SOURCES, SPECIES_DIR, log, norm_sci, read_json, slugify, write_json  # noqa: E402

REGION_ORDER = ["Tinamiformes"]  # unused placeholder to keep import tidy


def wiki_url(lang: str, title: str | None) -> str | None:
    if not title:
        return None
    return f"https://{lang}.wikipedia.org/wiki/{title.replace(' ', '_')}"


def family_names(sci: str, ebird_names: dict, wd: dict | None) -> dict:
    """en/es from eBird; ru from Wikidata (label, else ru Wikipedia title), null when missing or Latin.

    eBird has no Russian family names (its `ru` is the English one), so the site falls back to English."""
    names = {"en": ebird_names.get("en"), "es": ebird_names.get("es"), "ru": None}
    if wd:
        ru = wd["labels"].get("ru") or wd.get("ruwiki")
        if ru and ru.lower() != sci.lower() and re.search(r"[а-яё]", ru, re.I) and "(" not in ru:
            names["ru"] = ru
    return names


def endemics_report(aco: dict, chaparro: dict, index: list[dict], src: dict) -> None:
    """Log and write data/sources/endemics_report.md: ACO endemics vs Chaparro-Herrera et al. 2024."""
    if not src:
        return
    aco_e = {k for k, a in aco.items() if a["endemic"]}
    ch_e = {k for k, v in chaparro.items() if v["category"] == "endemic"}
    only_aco = sorted(aco_e - ch_e)
    only_ch = sorted(ch_e - aco_e)
    counts = src.get("counts", {})
    lines = [
        "# Endemics: ACO 2022 vs Chaparro-Herrera et al. 2024",
        "",
        "Generated by `pipeline/steps/build_species.py`. `colombia.endemic` stays ACO; "
        "`colombia.near_endemic` and `colombia.endemic_source` come from Chaparro-Herrera et al. 2024 (Anexo 3, CC BY-NC 4.0).",
        "",
        f"- Anexo 3 taxa: {src.get('count')} (endemic {counts.get('endemic', 0)}, near-endemic {counts.get('near_endemic', 0)}, "
        f"of interest {counts.get('of_interest', 0)}, insufficient info {counts.get('insufficient_info', 0)})",
        f"- Matched to the ACO list: {len(chaparro)}",
        f"- ACO endemics: {len(aco_e)}; Chaparro-Herrera endemics: {len(ch_e)}; both: {len(aco_e & ch_e)}",
        "",
        f"## Endemic in ACO, not in Chaparro-Herrera ({len(only_aco)})",
        "",
    ]
    lines += [f"- *{aco[k]['sci_name']}*: Chaparro-Herrera {chaparro[k]['code'] if k in chaparro else 'not listed'}" for k in only_aco] or ["- none"]
    lines += ["", f"## Endemic in Chaparro-Herrera, not in ACO ({len(only_ch)})", ""]
    lines += [f"- *{aco[k]['sci_name']}*: ACO status {aco[k]['status']['raw']}" for k in only_ch] or ["- none"]
    (SOURCES / "endemics_report.md").write_text("\n".join(lines) + "\n")
    log(f"  endemics: ACO {len(aco_e)}, Chaparro-Herrera {len(ch_e)}, both {len(aco_e & ch_e)}; "
        f"near-endemic {sum(1 for i in index if i['near_endemic'])}")
    for k in only_aco:
        log(f"    ACO-only endemic: {aco[k]['sci_name']} (Chaparro-Herrera: {chaparro[k]['code'] if k in chaparro else 'not listed'})")
    for k in only_ch:
        log(f"    Chaparro-Herrera-only endemic: {aco[k]['sci_name']} (ACO: {aco[k]['status']['raw']})")


def main() -> None:
    aco = read_json(SOURCES / "aco.json")["species"]
    ebird = read_json(SOURCES / "ebird.json")
    ebird_sp, ebird_fam = ebird["species"], ebird["families"]
    name_map = read_json(SOURCES / "ebird_name_map.json")
    birdbase = read_json(SOURCES / "birdbase.json")["species"]
    wikidata = read_json(SOURCES / "wikidata.json")["species"]
    aco_to_ebird = {k: k for k in aco}
    for k, v in {**name_map["auto_by_english_name"], **name_map["manual"]}.items():
        aco_to_ebird[k] = norm_sci(v)

    fam_names = (read_json(SOURCES / "family_names.json") or {}).get("families", {})
    # Chaparro-Herrera et al. 2024 (step `endemics`), keyed by ACO key. ACO's `endemic` flag stays canonical.
    endemics_src = read_json(SOURCES / "endemics.json") or {}
    chaparro = {v["aco_key"]: v for v in endemics_src.get("species", {}).values() if v.get("aco_key")}
    if not endemics_src:
        log("  WARNING: data/sources/endemics.json missing, run step `endemics`; near_endemic will be false")

    # Carry over fields filled by later steps (upload, wikipedia, sounds) so a rebuild does not wipe them.
    SPECIES_DIR.mkdir(parents=True, exist_ok=True)
    preserved: dict[str, dict] = {}
    for p in SPECIES_DIR.glob("*.json"):
        old = read_json(p) or {}
        preserved[p.stem] = {k: old[k] for k in ("photos", "texts", "sounds") if old.get(k)}
    old_files = {p.stem for p in SPECIES_DIR.glob("*.json")}

    index = []
    families: dict[str, dict] = {}
    slugs: dict[str, str] = {}
    for key, a in sorted(aco.items(), key=lambda kv: ebird_sp.get(aco_to_ebird[kv[0]], {}).get("taxon_order", 1e9)):
        e = ebird_sp[aco_to_ebird[key]]
        b = birdbase.get(key, {})
        w = wikidata.get(key, {})
        sci = e["sci_name"]
        slug = slugify(sci)
        if slug in slugs:  # two ACO taxa lumped into one Clements species
            slug = slugify(a["sci_name"])
        slugs[slug] = key

        name_ru = e["names"].get("ru") or None
        name_ru_source = "ebird" if name_ru else None
        if not name_ru and w.get("labels", {}).get("ru"):
            name_ru, name_ru_source = w["labels"]["ru"], "wikidata"

        fam_code = e["family_code"]
        fam = ebird_fam.get(fam_code, {})
        families.setdefault(
            fam_code,
            {
                "code": fam_code,
                "sci": fam.get("sci") or a["family"],
                "order": fam.get("order") or a["order"],
                "names": family_names(fam.get("sci") or a["family"], fam.get("names", {}), fam_names.get(fam_code)),
                "species_count": 0,
                "slug": slugify(fam.get("sci") or a["family"]),
            },
        )["species_count"] += 1

        ch = chaparro.get(key)
        near_endemic = bool(ch and ch["category"] == "near_endemic")
        endemic_source = (
            {"category": ch["category"], "code": ch["code"], "source": ch["source"]} if ch else None
        )

        taxonomy_note = None
        if norm_sci(sci) != key:
            taxonomy_note = f"ACO/SACC lists this as {a['sci_name']}; eBird/Clements uses {sci}."

        rec = {
            "id": slug,
            "sci_name": sci,
            "sci_name_aco": a["sci_name"],
            "authorship": a["authorship"],
            "taxonomy_note": taxonomy_note,
            "names": {
                "en": e["names"].get("en") or a["name_en_aco"],
                "ru": name_ru,
                "es": e["names"].get("es") or None,
                "en_aco": a["name_en_aco"],
            },
            "name_ru_source": name_ru_source,
            "ebird_code": e["code"],
            "taxon_order": e["taxon_order"],
            "order": e.get("order") or a["order"],
            "family": {"code": fam_code, "sci": fam.get("sci") or a["family"], "en": fam.get("names", {}).get("en")},
            "genus": sci.split()[0],
            "colombia": {
                "status": a["status"]["codes"],
                "status_uncertain": a["status"]["uncertain"],
                "status_raw": a["status"]["raw"],
                "endemic": a["endemic"],
                "near_endemic": near_endemic,
                "endemic_source": endemic_source,
                "introduced": a["introduced"],
                "migration_note": a["migration_note"],
                "libro_rojo": a["libro_rojo"],
                "habitat_aco": a["habitat_aco"],
            },
            "iucn": {"aco_2022": a["iucn"], "birdbase_2024": b.get("iucn_2024"), "wikidata": w.get("iucn_status")},
            "traits": {
                "elevation_m": b.get("elevation"),
                "mass_g": b.get("mass_g"),
                "primary_habitat": b.get("primary_habitat"),
                "habitats": b.get("habitats", []),
                "habitat_breadth": b.get("habitat_breadth"),
                "primary_diet": b.get("primary_diet"),
                "diet_desc": b.get("diet_desc"),
                "mobility": b.get("mobility"),
                "range_restricted": b.get("range_restricted"),
            },
            "ids": {
                "wikidata": w.get("qid"),
                "gbif": a.get("gbif_key") or w.get("gbif_key"),
                "avibase": w.get("avibase_id"),
                "inaturalist": w.get("inaturalist_id"),
                "iucn": w.get("iucn_id"),
                "xeno_canto": w.get("xeno_canto"),
                "birdbase": b.get("birdbase_id"),
            },
            "links": {
                "ebird": f"https://ebird.org/species/{e['code']}",
                "wikipedia": {lang: wiki_url(lang, w.get("wikipedia", {}).get(lang)) for lang in ("en", "es", "ru")},
                "commons_category": (
                    f"https://commons.wikimedia.org/wiki/Category:{w['commons_category'].replace(' ', '_')}"
                    if w.get("commons_category") else None
                ),
                "xeno_canto": f"https://xeno-canto.org/explore?query={sci.replace(' ', '+')}",
                "inaturalist": f"https://www.inaturalist.org/taxa/{w['inaturalist_id']}" if w.get("inaturalist_id") else None,
            },
            "wikidata_images": w.get("images", []),
            # Filled by later pipeline steps (kept from the previous build, see `preserved`)
            "photos": preserved.get(slug, {}).get("photos", []),
            "texts": preserved.get(slug, {}).get("texts", {}),
            "sounds": preserved.get(slug, {}).get("sounds", []),
            # Filled by agents (content/species/<slug>.md) — kept null here on purpose
            "difficulty": None,
        }
        write_json(SPECIES_DIR / f"{slug}.json", rec)
        index.append(
            {
                "id": slug,
                "sci": sci,
                "en": rec["names"]["en"],
                "ru": name_ru,
                "family": fam_code,
                "order": rec["order"],
                "taxon_order": e["taxon_order"],
                "status": rec["colombia"]["status"],
                "endemic": a["endemic"],
                "near_endemic": near_endemic,
                "iucn": a["iucn"],
                "elev": [b.get("elevation", {}).get("min"), b.get("elevation", {}).get("max")] if b.get("elevation") else None,
                "habitat": b.get("primary_habitat"),
                "photo": rec["photos"][0]["sizes"]["thumb"] if rec["photos"] else None,
            }
        )

    endemics_report(aco, chaparro, index, endemics_src)

    for stale in old_files - {i["id"] for i in index}:
        (SPECIES_DIR / f"{stale}.json").unlink()
    write_json(DATA / "species_index.json", index)
    fam_list = sorted(families.values(), key=lambda f: min(i["taxon_order"] for i in index if i["family"] == f["code"]))
    write_json(DATA / "families.json", fam_list)
    log(f"built {len(index)} species, {len(fam_list)} families")
    log(f"  ru names: {sum(1 for i in index if i['ru'])} (ebird {sum(1 for i in index if i['ru'] and read_json(SPECIES_DIR / (i['id'] + '.json'))['name_ru_source']=='ebird')})")
    log(f"  photos kept: {sum(1 for i in index if i['photo'])}; families with ru name: {sum(1 for f in fam_list if f['names'].get('ru'))}")
    log(f"  elevation: {sum(1 for i in index if i['elev'])}")


if __name__ == "__main__":
    main()
